version: '2'
services:
    bugtracker-app:
        image: bugtracker
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://bugtracker-mysql:3306/bugtracker?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=bugtracker-elasticsearch:9300
        ports:
            - 8080:8080
    bugtracker-mysql:
        extends:
            file: mysql.yml
            service: bugtracker-mysql
    bugtracker-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: bugtracker-elasticsearch
